export let trackingModel = {
  id: "",
  username: "",
  track_id: "",
  weight: "",
  round_boat: "",
  pic1_filename: "",
  pic2_filename: "",
  created_at: "",
  updated_at: "",
  date: new Date().toISOString().split("T")[0],
  channel: "",
  box_id: "",
  url: "",
  check1: "",
  check2: "",
  price: "",
  point: "",
  addPoint: "",
  q: "",
};
