const Manage_Data = [
  {
    id: 1,
    label: "Username",
    name: "username",
    type: "text",
    col: "col-6 mb-3",
    placeholder: "Enter Username",
  },
  {
    id: 2,
    label: "Name",
    name: "name",
    type: "text",
    col: "col-6 mb-3",
    placeholder: "Enter Name",
  },
  {
    id: 3,
    label: "Phone",
    name: "phone",
    type: "text",
    col: "col-6 mb-3",
    placeholder: "Enter Phone",
  },
  {
    id: 5,
    label: "Contact",
    name: "contact",
    type: "text",
    col: "col-6 mb-3",
    placeholder: "Enter Contact",
  },
  {
    id: 4,
    label: "Address",
    name: "address",
    type: "text",
    col: "col-12 mb-3",
    placeholder: "Enter Address",
  },
  {
    id: 6,
    label: "Old Point",
    name: "point_old",
    type: "number",
    col: "col-6 mb-3",
    placeholder: "Enter Old Point",
  },
  {
    id: 7,
    label: "New Point",
    name: "point_new",
    type: "number",
    col: "col-6 mb-3",
    placeholder: "Enter New Point",
  },
];
export default Manage_Data;
